spring.application.name=recursoshumanos
spring.profiles.active=prod
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework=INFO
server.error.include-message=always
